### ISSUE TITLE
Feature request: Loading svg from file

### ISSUE THREAD

**Issue by TotalKrill** [coastalwhite/WasmSVGGraphics#1]
What would make this library even more promising is being able to use it to animate existing svg files, Ill just add this issue here to be notified if this ever happens :)

**Comment by coastalwhite** [comment]
I have been looking into this feature, and I agree that this should be possible. Yet it would most likely be implemented in a dependency of this library: [svg_definitions](https://github.com/coastalwhite/svg_definitions). Since I also maintain that crate, you should probably keep an eye out there.

I will close this issue, when that is implemented there.

**Comment by coastalwhite** [comment]
Hello,

Good news! From version _1.0.2_ this will be implemented.

Have a look at the main examples of the [svg_definitions docs](https://docs.rs/svg_definitions/0.3.0/svg_definitions/) to see how it works.

**Make sure to activate the feature "parsing" to be able to use it.**

Two new functions were added to svg_definitions, which will also be available from wasm_svg_graphics:
* `fn parse_text(xml: &str) -> Result<svg_definitions::Element, ParseError>`
* `fn parse_file(path: &str) -> Result<svg_definitions::Element, ParseError>`

Thanks for the suggestion and have a nice day!
